// This file was generated by a custom prisma generator, do not edit manually.
export const TargetAudience = {
  MEN: "MEN",
  WOMEN: "WOMEN",
  KIDS: "KIDS",
  UNISEX: "UNISEX",
} as const;

export type TargetAudience = (typeof TargetAudience)[keyof typeof TargetAudience];

export const DeliveryStatus = {
  PENDING: "PENDING",
  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",
  FAILED: "FAILED",
  REJECTED: "REJECTED",
} as const;

export type DeliveryStatus = (typeof DeliveryStatus)[keyof typeof DeliveryStatus];

export const ClothType = {
  COTTON: "COTTON",
  DENIM: "DENIM",
  POLYESTER: "POLYESTER",
  SILK: "SILK",
  WOOL: "WOOL",
  LINEN: "LINEN",
  LEATHER: "LEATHER",
  SATIN: "SATIN",
  VELVET: "VELVET",
  CHIFFON: "CHIFFON",
  FLANNEL: "FLANNEL",
  GABARDINE: "GABARDINE",
  JERSEY: "JERSEY",
  LACE: "LACE",
  LYCRA: "LYCRA",
  NYLON: "NYLON",
  RAYON: "RAYON",
  SPANDEX: "SPANDEX",
  TWILL: "TWILL",
} as const;

export type ClothType = (typeof ClothType)[keyof typeof ClothType];

export const OrderType = {
  DELIVERY: "DELIVERY",
  PICKUP: "PICKUP",
} as const;

export type OrderType = (typeof OrderType)[keyof typeof OrderType];

export const PaymentMethod = {
  CREDIT_CARD: "CREDIT_CARD",
  DEBIT_CARD: "DEBIT_CARD",
} as const;

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod];

export const OrderStatus = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  ASSIGNED_TO_DELIVERY: "ASSIGNED_TO_DELIVERY",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  COMPLETED: "COMPLETED",
} as const;

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export const UserRole = {
  ADMIN: "ADMIN",
  CUSTOMER: "CUSTOMER",
  EMPLOYEE: "EMPLOYEE",
} as const;

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const Size = {
  XSMALL: "XSMALL",
  SMALL: "SMALL",
  MEDIUM: "MEDIUM",
  LARGE: "LARGE",
  XLARGE: "XLARGE",
  XXLARGE: "XXLARGE",
  XXXLARGE: "XXXLARGE",
} as const;

export type Size = (typeof Size)[keyof typeof Size];

export const Color = {
  RED: "RED",
  BLUE: "BLUE",
  GREEN: "GREEN",
  YELLOW: "YELLOW",
  BLACK: "BLACK",
  WHITE: "WHITE",
  ORANGE: "ORANGE",
  PURPLE: "PURPLE",
  PINK: "PINK",
  BROWN: "BROWN",
  GREY: "GREY",
  NAVY: "NAVY",
  WHEAT: "WHEAT",
  DARK_BROWN: "DARK_BROWN",
  CORE_BLACK: "CORE_BLACK",
  EARTH: "EARTH",
  SILVER: "SILVER",
  ROYAL_BLUE: "ROYAL_BLUE",
  GRAY: "GRAY",
} as const;

export type Color = (typeof Color)[keyof typeof Color];

export const ReturnMethod = {
  UPS_STORE: "UPS_STORE",
  IN_STORE: "IN_STORE",
} as const;

export type ReturnMethod = (typeof ReturnMethod)[keyof typeof ReturnMethod];

export const ReturnStatus = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  RECEIVED: "RECEIVED",
  REFUNDED: "REFUNDED",
  CANCELLED: "CANCELLED",
} as const;

export type ReturnStatus = (typeof ReturnStatus)[keyof typeof ReturnStatus];

export const Gender = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  OTHER: "OTHER",
} as const;

export type Gender = (typeof Gender)[keyof typeof Gender];

export const EmployeeRegistrationRequestStatus = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
} as const;

export type EmployeeRegistrationRequestStatus = (typeof EmployeeRegistrationRequestStatus)[keyof typeof EmployeeRegistrationRequestStatus];
